global:
  scrape_interval: 5s

scrape_configs:
  - job_name: gateway
    metrics_path: /metrics
    scheme: http
    tls_config:
      insecure_skip_verify: true  # For self-signed certs (remove in production)
    static_configs:
      - targets:
          - host.docker.internal:8081      # Docker service name
